### ISSUE TITLE
How to stop auto upgrade on splunk docker?

### ISSUE THREAD

**Issue by jamesgunja** [splunk/docker-splunk-legacy#21]
How to stop auto upgrade on splunk docker?

**Comment by Kahn** [comment]
There is not an auto upgrade process that I am aware of. If you want to pin to a version then use the docker tags. 

**docker pull outcoldman/splunk:6.4.2** will never pull a new version. If you used docker pull outcoldman/splunk:latest then when the image is next released and the container restarted your version will "update"

Can you paste your "docker ps" output where this issue is happening?

**Comment by outcoldman** [comment]
@jamesgunja could you clarify what do you mean by that?

**Comment by daniloascione** [comment]
Maybe it is the same issue... 

docker-compose up
Starting splunkdocker_splunk_1
Attaching to splunkdocker_splunk_1
splunk_1  | tcgetattr: Inappropriate ioctl for device
splunk_1  | WARNING: error changing terminal modes - password will echo!
splunk_1  | Perform migration and upgrade without previewing configuration changes? [y/n]
splunk_1  |
splunk_1  | This appears to be an upgrade of Splunk.
splunk_1  | --------------------------------------------------------------------------------)
splunk_1  |
splunk_1  | Splunk has detected an older version of Splunk installed on this machine. To
splunk_1  | finish upgrading to the new version, Splunk's installer will automatically
splunk_1  | update and alter your current configuration files. Deprecated configuration
splunk_1  | files will be renamed with a .deprecated extension.
splunk_1  |
splunk_1  | You can choose to preview the changes that will be made to your configuration
splunk_1  | files before proceeding with the migration and upgrade:
splunk_1  |
splunk_1  | If you want to migrate and upgrade without previewing the changes that will be
splunk_1  | made to your existing configuration files, choose 'y'.
splunk_1  | If you want to see what changes will be made before you proceed with the
splunk_1  | upgrade, choose 'n'.
splunk_1  |
splunk_1  |
splunkdocker_splunk_1 exited with code 1

**Comment by daniloascione** [comment]
I've added the --answer-yes to solve the issue.
In docker-compose.yml :
environment: 
      - SPLUNK_START_ARGS=--accept-license --answer-yes

**Comment by outcoldman** [comment]
@daniloascione yep, that makes sense.

**Comment by jamesgunja** [comment]
Sorry for the delay in responding. Correct this is same issue I am facing too. Look like --answer-yes solves this. Thank-you guys!!
splunk_1 | tcgetattr: Inappropriate ioctl for device
splunk_1 | WARNING: error changing terminal modes - password will echo!
splunk_1 | Perform migration and upgrade without previewing configuration changes? [y/n]
splunk_1 |
splunk_1 | This appears to be an upgrade of Splunk.
splunk_1 | --------------------------------------------------------------------------------)
splunk_1 |
splunk_1 | Splunk has detected an older version of Splunk installed on this machine. To
splunk_1 | finish upgrading to the new version, Splunk's installer will automatically
splunk_1 | update and alter your current configuration files. Deprecated configuration
splunk_1 | files will be renamed with a .deprecated extension.
splunk_1 |
splunk_1 | You can choose to preview the changes that will be made to your configuration
splunk_1 | files before proceeding with the migration and upgrade:
splunk_1 |
splunk_1 | If you want to migrate and upgrade without previewing the changes that will be
splunk_1 | made to your existing configuration files, choose 'y'.
splunk_1 | If you want to see what changes will be made before you proceed with the
splunk_1 | upgrade, choose 'n'.
splunk_1 |
splunk_1 |
splunkdocker_splunk_1 exited with code 1

**Comment by outcoldman** [comment]
Great, thank you for confirming, updated the README.md https://github.com/outcoldman/docker-splunk/commit/80e8f69dc45faa14b29531aded6e4859e131e6d5
