### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by guenichone** [splunk/docker-splunk-legacy#22]
Hi,

After a long time of usage without any problem, I finally restarted the running container (after modifying the host hardware), now the image doesn't want to start any more on my previous volume.

btool.log shows the following 

08-29-2016 09:18:07.764 ERROR IniFile - Cannot open file=/opt/splunk/etc/system/local/server.conf for parsing: Permission denied
08-29-2016 09:18:07.766 ERROR UsernameMapper - Cannot create username mapping file: /opt/splunk/etc/users/users.ini: Permission denied
08-29-2016 09:18:07.766 ERROR IniFile - Cannot open file=/opt/splunk/etc/users/users.ini for parsing: Permission denied
08-29-2016 09:18:07.766 ERROR UsernameMapper - Error opening username mapping file: /opt/splunk/etc/users/users.ini
08-29-2016 09:18:07.773 ERROR ConfObjectManagerDB - Cannot initialize: /opt/splunk/etc/apps/launcher/metadata/local.meta: Permission denied
08-29-2016 09:18:07.773 ERROR ConfObjectManagerDB - Cannot initialize: /opt/splunk/etc/apps/search/metadata/local.meta: Permission denied
08-29-2016 09:18:07.773 ERROR ConfObjectManagerDB - Cannot initialize: /opt/splunk/etc/apps/splunk_management_console/metadata/local.meta: Permission denied
08-29-2016 09:18:07.773 ERROR ConfObjectManagerDB - Cannot initialize: /opt/splunk/etc/apps/user-prefs/metadata/local.meta: Permission denied
08-29-2016 09:18:07.776 ERROR ConfObjectManagerDB - Cannot initialize: /opt/splunk/etc/system/metadata/local.meta: Permission denied
08-29-2016 09:18:07.776 ERROR ConfObjectManagerDB - Cannot initialize: /opt/splunk/etc/apps/learned/metadata/local.meta: Permission denied

The user rights of the folder look like the following (in the host, then user are not displayed as splunk:splunk) :

![image](https://cloud.githubusercontent.com/assets/1672227/18056075/c05dd326-6e0a-11e6-93a6-71bff8963a1f.png)

I tried to boot the image on a new volume, it seems the problem doesn't occur.

Do you have any idea how I can fix that ?

Thanks !

**Comment by guenichone** [comment]
Ok issue fixed by doing a recusrive chmod on folder. I don't know why the permissions changed.

**Comment by outcoldman** [comment]
Possible that you have executed something or tried to restart splunk not with the default user we use in the container (`splunk`), this is why permission messed up
