### ISSUE TITLE
Docker Hub

### ISSUE THREAD

**Issue by chadwagoner** [splunk/docker-splunk-legacy#23]
Is docker-splunk no longer listed on Docker Hub?

**Comment by outcoldman** [comment]
The Splunk Release team has incorporated the work I have has done in to its build process. We're getting close to putting our images in Docker Store, so there's no longer a need for me to maintain my own repository. Feel free to use my Dockerfile if you want to build your own images.

**Comment by historus** [comment]
I really appreciate the work you do but removing it from docker hub before the replacement is released breaks a lot of integrations and workflows.

**Comment by outcoldman** [comment]
@historus yes, that is true. I feel your pain and I personally sorry for that. There were some reasons which required me to remove the image from the Docker Hub. I knew that this can bring some issues to existing image users, this is why I kept github repository, so folks will be able to build their own images.

We know about this issue and Splunk Inc is working hard with Docker to make the images available. I am trying to help ad push as much as I can.

**Comment by historus** [comment]
Appreciated. I forked and built it on my own now, thanks for keeping the git repo public.

**Comment by outcoldman** [comment]
Repository has been moved to the splunk/docker-splunk, latest image is under u/splunk account on hub.docker.com, see https://hub.docker.com/u/splunk/

I am happy to close this issue!

**Comment by halr9000** [comment]
LGTM ;)
