### ISSUE TITLE
Mounting volumes should be document with named volumed and not data only containers

### ISSUE THREAD

**Issue by chernals** [splunk/docker-splunk-legacy#25]
The readme mentions

Start a Splunk Enterprise container and mount the necessary container volumes

docker run --name vsplunk -v /opt/splunk/etc -v /opt/splunk/var busybox
docker run --hostname splunk --name splunk --volumes-from=vsplunk -p 8000:8000 -d -e "SPLUNK_START_ARGS=--a

Should this be updated to use named volumes instead (as of Docker 1.9.0)?

**Comment by ahmed-bacha** [comment]
Yes, it would be interesting since some users prefer to have more control.

So, when do you plan to update it ?

**Comment by halr9000** [comment]
If it's a basic doc update, those are easy, and we accept PRs for those as well. I say just go ahead and work up a new example if you like.
