### ISSUE TITLE
Low Disk Space

### ISSUE THREAD

**Issue by old-coursevector** [splunk/docker-splunk-legacy#3]
I am getting a low disk space warning (Under 5GB free) after a few weeks of use and it has caused Splunk to stop indexing and not allow users to use the web interface. Moving the Splunk setting to 2GB restored functionality, but is obviously a temporary solution. 

I am using data volume containers as suggested in the readme.

When I run docker ps -s I get:
14.08 MB (virtual 546.3 MB)

Is there another way I should be checking disk usage?

Any ideas on how to fix this or what may be happening?

Thanks.

**Comment by jeff-minard-ck** [comment]
I had the same thing, but it is related to disk space on the host, since docker doesn't really impose any direct limits itself (usually, you can, but if you were doing that you'd know).

**Comment by outcoldman** [comment]
@coursevector how much disk space you actually have on your host machine where you run docker? You can run

```
df -h
```

Also you can run 

```
docker info 
```

To find where is your `Root Dir:` - this is actually where the data from data volume container will be stored.

**Comment by old-coursevector** [comment]
Ignore this. I tracked it back to another container.
