### ISSUE TITLE
How do we configure the universal forwarder to use SSL Certs?

### ISSUE THREAD

**Issue by dmcnaught** [splunk/docker-splunk-legacy#48]
There doesn't seem to be inputs/options described for that.
Can we do it?
Thanks
--Duncan

**Comment by mchene** [comment]
@dmcnaught - Hey Duncan, can you confirm you are referring to using your own certificates as documented here: http://docs.splunk.com/Documentation/Splunk/6.6.2/Security/ConfigureSplunkforwardingtousesignedcertificates? 

If so, how would you like to reference and configure the certs? e.g., 
Cert Location: shared data volume configured on the UF container image?
Cert configuration: environment parameters to the UF container image that would automatically configure the $SPLUNK_HOME/etc/system/local/inputs.conf, outputs.conf and server.conf with the specified options?  

Another option would be for you to create your own image off of our public one that would include your certs and required UF configurations.  Thoughts?

**Comment by dmcnaught** [comment]
For version 6.3.1 I added these lines to the Dockerfile and it was working fine.
```bash
COPY splunkforwarder/ca.pem ${SPLUNK_HOME}/etc/auth/ca.pem
COPY splunkforwarder/cacert.pem ${SPLUNK_HOME}/etc/auth/cacert.pem
COPY splunkforwarder/server.pem ${SPLUNK_HOME}/etc/auth/server.pem
COPY splunkforwarder/inputs.conf ${SPLUNK_HOME}/etc/system/local/inputs.conf
```
We recently generated a new cert with a non-default SSL password, and upgraded our server to 6.6 and I haven't been able to get connected. I'm seeing this error in the startup logs: `ERROR SSLCommon - Can't read key file /opt/splunk/etc/auth/server.pem errno=218570875 error:0D07207B:asn1 encoding routines:ASN1_get_object:header too long.` and then the `splunk add forward-server` command in entrypoint.sh hangs.

**Comment by dmcnaught** [comment]
Turns out my cert was missing a line break, not sure how that happened...
I'm able to configure the container with ssl with the above addition of certs, and then on the command line starting with the following args:
-e SPLUNK_START_ARGS="--accept-license" -e "SPLUNK_FORWARD_SERVER=indexer.domain.com:9997" -e "SPLUNK_FORWARD_SERVER_ARGS=-ssl-cert-path /opt/splunk/etc/auth/server.pem -ssl-root-ca-path /opt/splunk/etc/auth/ca.pem -ssl-password password"

**Comment by dmcnaught** [comment]
Thanks for providing this container! It's very much appreciated and used by us.
