### ISSUE TITLE
Branch 7.0.1 not available on Docker Hub

### ISSUE THREAD

**Issue by therealmysteryman** [splunk/docker-splunk-legacy#63]
The branch 7.0.1 is not exposed to the Docker Repository. Wondering how close we are to have it available ?

**Comment by n00badmin** [comment]
I'll look at getting it out there asap.

**Comment by matthewmodestino** [comment]
I'll get on creating the PR asap!

**Comment by therealmysteryman** [comment]
Thanks :)
