### ISSUE TITLE
entrypoint.sh: no such file or directory

### ISSUE THREAD

**Issue by dmuth** [splunk/docker-splunk-legacy#76]
How to reproduce this:

- In the main directory, run `docker build . -t`

It looks like the path to the file is wrong.  No big deal, but thought you'd like to know.

-- Doug

**Comment by renaudholcombe** [comment]
You need to run the `docker build` command from within either the "enterprise" or "universalforwarder" directories (based on which image you're attempting to build).

**Comment by dmuth** [comment]
Yeah, I eventually did that.

There used to be a `Dockerfile` in the root directory when I filed the bug.  

That since seems to have been removed, so I'll close this bug as it is no longer relevant.

-- Doug
