### ISSUE TITLE
Include rfc5424-syslog plugin in *-monitor image by default

### ISSUE THREAD

**Issue by aegershman** [splunk/docker-splunk-legacy#90]
As a cloud foundry operator, [I want to use Splunk to ingest my `rsyslog` platform logs.](
https://docs.cloudfoundry.org/devguide/services/integrate-splunk.html#config) Therefore, I would like the Splunk `<version>-monitor` docker image to come pre-packed with the [`RFC5424 Syslog`](https://splunkbase.splunk.com/app/978/) application by default.

The `*-monitor` image comes packed with the `Docker Monitoring Dockerfile` goodie, and it would be very helpful for day-to-day operations if the `RFC5424 Syslog` were packed as well. (

(Unfortunately, the provided `syslog` source format does not seem to parse logs from cloud foundry's `rsyslog` properly, whereas the RFC5424 Syslog does.)

Thank you for your consideration.

**Comment by matthewmodestino** [comment]
Hey Aaron!

Thanks for checking out our containers!

I am not sure we would get into hosting a ton of different pre-baked apps, currently we are focused on official support, for the base images.

In the meantime, you could easily build your own versions of the container. You just need to copy the configs into the container. Have you checked out the dockerfile, or tried to create your own?

Would be happy to assist you in getting going! 

You can join us in the slack chat for some realtime help on that splk.it/slack in the #docker room.

**Comment by aegershman** [comment]
I totally understand, I can see how that would get messy pretty quick. Just figured I'd feel things out. Thanks for your time.
