### ISSUE TITLE
Kubernetes/helm chart packaging?

### ISSUE THREAD

**Issue by aegershman** [splunk/docker-splunk-legacy#92]
As an admin, I would like to manage my Splunk deployments on Kubernetes via `helm` chart(s).

[I am currently trying to write a helm chart for deploying a standalone heavy forwarder](https://github.com/aegershman/charts/tree/master/src/splunk), but I am very new to k8, helm, and Splunk in general. Therefore, I'm concerned that what I write will be ... well, crap.

Are there any plans for the Splunk team to offer easily consumable helm chart(s) for maintaining Splunk clusters? 

I can see charts for different use cases, such as:
- chart for standalone heavy forwarder / local indexer (like I am _kind of_ writing)
- chart for cluster of headless forwarders
- chart for cluster of indexers
- etc.

I realize this repository is mostly for holding the base images / basic config for Splunk on docker images, so forgive me if the scope of this question is too broad

EDIT, I now see there's helm deployments in-progress. Just not my exact use-case: https://github.com/splunk/splunk-connect-for-kubernetes/tree/master/helm-chart/splunk-kubernetes-logging

**Comment by matthewmodestino** [comment]
Hey Aaron!

We are working hard internally to get docker moved into offical support, so keep your ear to the ground, as that should allow us to provide better guidance on deployment methods in kube.

In the meantime come join us on slack (splk.it/slack) in the #kubernetes room and I’d be happy to share some manifests I have created that you could templitize with helm! my handle is @mattymo!
